spring:
  application:
    name: UrlShortener

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false

springdoc:
  api-docs:
    path: /swagger.html
  override-with-generic-response: false