server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: "sa"
    password: ""
    url: "jdbc:h2:mem:test"

  jpa:
    show-sql: true


logging:
  level:
    root: INFO
    web: DEBUG