spring:
  application:
    name: UrlShortener

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false